# Generated by Django 2.1 on 2020-01-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roli_number', models.IntegerField(unique=True)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=100)),
                ('student_section', models.CharField(max_length=100)),
                ('telugu_marks', models.IntegerField()),
                ('hindi_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('mathamtics_marks', models.IntegerField()),
                ('scince_marks', models.IntegerField()),
                ('social_marks', models.IntegerField()),
            ],
        ),
    ]
