# Generated by Django 2.1 on 2020-01-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdataapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='mathamtics_marks',
            new_name='mathematics_marks',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='student_roli_number',
            new_name='student_roll_number',
        ),
    ]
